// ============================================================
// slots.ts - 16 משבצות הפרסום הפנויות בטור הימני.
//
// הוצאו מתוך RightAdBanner.svelte כדי שגם מסך הניהול יוכל להציג את
// מלאי המשבצות. כל מחלקות Tailwind נשארות מחרוזות מלאות — ה-JIT מוחק
// כל מחלקה שנבנית בזמן ריצה.
// ============================================================

export interface AdSlotStyle {
    text: string;
    description: string;
    borderColor: string;
    bgColor: string;
    hoverBorder: string;
    hoverBg: string;
    textColor: string;
    hoverText: string;
    buttonColor: string;
}

export const AD_SLOTS: AdSlotStyle[] = [
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-orange-500/60",
            bgColor: "bg-orange-900/45",
            hoverBorder: "hover:border-orange-500",
            hoverBg: "hover:bg-orange-800/60",
            textColor: "text-orange-400",
            hoverText: "group-hover:text-orange-200",
            buttonColor: "bg-orange-600 hover:bg-orange-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-blue-500/60",
            bgColor: "bg-blue-900/45",
            hoverBorder: "hover:border-blue-500",
            hoverBg: "hover:bg-blue-800/60",
            textColor: "text-blue-400",
            hoverText: "group-hover:text-blue-200",
            buttonColor: "bg-blue-600 hover:bg-blue-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-green-500/60",
            bgColor: "bg-green-900/45",
            hoverBorder: "hover:border-green-500",
            hoverBg: "hover:bg-green-800/60",
            textColor: "text-green-400",
            hoverText: "group-hover:text-green-200",
            buttonColor: "bg-green-600 hover:bg-green-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-amber-500/60",
            bgColor: "bg-amber-900/45",
            hoverBorder: "hover:border-amber-500",
            hoverBg: "hover:bg-amber-800/60",
            textColor: "text-amber-400",
            hoverText: "group-hover:text-amber-200",
            buttonColor: "bg-amber-600 hover:bg-amber-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-purple-500/60",
            bgColor: "bg-purple-900/45",
            hoverBorder: "hover:border-purple-500",
            hoverBg: "hover:bg-purple-800/60",
            textColor: "text-purple-400",
            hoverText: "group-hover:text-purple-200",
            buttonColor: "bg-purple-600 hover:bg-purple-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-red-500/60",
            bgColor: "bg-red-900/45",
            hoverBorder: "hover:border-red-500",
            hoverBg: "hover:bg-red-800/60",
            textColor: "text-red-400",
            hoverText: "group-hover:text-red-200",
            buttonColor: "bg-red-600 hover:bg-red-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-indigo-500/60",
            bgColor: "bg-indigo-900/45",
            hoverBorder: "hover:border-indigo-500",
            hoverBg: "hover:bg-indigo-800/60",
            textColor: "text-indigo-400",
            hoverText: "group-hover:text-indigo-200",
            buttonColor: "bg-indigo-600 hover:bg-indigo-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-teal-500/60",
            bgColor: "bg-teal-900/45",
            hoverBorder: "hover:border-teal-500",
            hoverBg: "hover:bg-teal-800/60",
            textColor: "text-teal-400",
            hoverText: "group-hover:text-teal-200",
            buttonColor: "bg-teal-600 hover:bg-teal-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-pink-500/60",
            bgColor: "bg-pink-900/45",
            hoverBorder: "hover:border-pink-500",
            hoverBg: "hover:bg-pink-800/60",
            textColor: "text-pink-400",
            hoverText: "group-hover:text-pink-200",
            buttonColor: "bg-pink-600 hover:bg-pink-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-yellow-500/60",
            bgColor: "bg-yellow-900/45",
            hoverBorder: "hover:border-yellow-500",
            hoverBg: "hover:bg-yellow-800/60",
            textColor: "text-yellow-400",
            hoverText: "group-hover:text-yellow-200",
            buttonColor: "bg-yellow-600 hover:bg-yellow-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-emerald-500/60",
            bgColor: "bg-emerald-900/45",
            hoverBorder: "hover:border-emerald-500",
            hoverBg: "hover:bg-emerald-800/60",
            textColor: "text-emerald-400",
            hoverText: "group-hover:text-emerald-200",
            buttonColor: "bg-emerald-600 hover:bg-emerald-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-fuchsia-500/60",
            bgColor: "bg-fuchsia-900/45",
            hoverBorder: "hover:border-fuchsia-500",
            hoverBg: "hover:bg-fuchsia-800/60",
            textColor: "text-fuchsia-400",
            hoverText: "group-hover:text-fuchsia-200",
            buttonColor: "bg-fuchsia-600 hover:bg-fuchsia-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-cyan-500/60",
            bgColor: "bg-cyan-900/45",
            hoverBorder: "hover:border-cyan-500",
            hoverBg: "hover:bg-cyan-800/60",
            textColor: "text-cyan-400",
            hoverText: "group-hover:text-cyan-200",
            buttonColor: "bg-cyan-600 hover:bg-cyan-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-rose-500/60",
            bgColor: "bg-rose-900/45",
            hoverBorder: "hover:border-rose-500",
            hoverBg: "hover:bg-rose-800/60",
            textColor: "text-rose-400",
            hoverText: "group-hover:text-rose-200",
            buttonColor: "bg-rose-600 hover:bg-rose-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-lime-500/60",
            bgColor: "bg-lime-900/45",
            hoverBorder: "hover:border-lime-500",
            hoverBg: "hover:bg-lime-800/60",
            textColor: "text-lime-400",
            hoverText: "group-hover:text-lime-200",
            buttonColor: "bg-lime-600 hover:bg-lime-500",
        },
        {
            text: "מקום פרסום",
            description: "יכול להיות שלך",
            borderColor: "border-sky-500/60",
            bgColor: "bg-sky-900/45",
            hoverBorder: "hover:border-sky-500",
            hoverBg: "hover:bg-sky-800/60",
            textColor: "text-sky-400",
            hoverText: "group-hover:text-sky-200",
            buttonColor: "bg-sky-600 hover:bg-sky-500",
        },
];
